
server:
  port: 8096
spring:
  #给项目来个名字
  application:
    name: rabbitmq-provider
  #配置rabbitMq 服务器
  rabbitmq:
    host:
    port: 5672
    username:
    password:
    # 是否返回回调
    publisher-returns: true
    template:
    #开启mandatory: true, basic.return方法将消息返还给生产者
      mandatory: true
      #虚拟host 可以不设置,使用server默认host  /
    virtual-host: test
    listener:
      simple:
        # 手动应答
        acknowledge-mode: manual
        # 最少消费者数量
        concurrency: 1
        # 最多消费者数量
        max-concurrency: 10
        # 支持重试
        retry:
          enabled: true
